### ISSUE TITLE
object has no attribute 'StreamHandler'

### ISSUE THREAD

**Issue by gretel** [pgularski/upysm#1]
on `MicroPython v1.17` the library installs fine but does not work for me:

```
>>> from pysm import State, StateMachine, Event
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/pysm/__init__.py", line 2, in <module>
  File "/lib/pysm/pysm.py", line 93, in <module>
AttributeError: 'module' object has no attribute 'StreamHandler'
```

think this class is not present.

**Comment by simons1008** [comment]
Hi, after upysm installation I got the same error.  

I use the hardware ESP32 Devkit C V4 and the IDE Thonny 3.3.13

**I found a workaround solution**
I observed the following messages from upip.install('upysm'):
Installing upysm 0.3.9 from https://files.pythonhosted.org/packages/4e/6d/c50d0ca1c6cf627830aaf1df619c18aa82519b0bceafa1f7b48a07c3032a/upysm-0.3.9.tar.gz
Installing micropython-collections.deque 0.1.3 from https://micropython.org/pi/collections.deque/collections.deque-0.1.3.tar.gz
Installing micropython-collections.defaultdict 0.3 from https://micropython.org/pi/collections.defaultdict/collections.defaultdict-0.3.tar.gz
Installing micropython-logging 0.3 from https://micropython.org/pi/logging/logging-0.3.tar.gz

**micropython-logging 0.3 is not the latest revision!** pypi.org lists micropython-logging 0.5.2
 
Therefore I deleted the old logging.py on my ESP32. 
I unpacked the file micropython-logging-0.5.2.tar.gz on my computer and copied the folder "logging" manually to my ESP32.

Now, the is no error message upon:
from pysm import State, StateMachine, Event
